# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def common_pods
	use_frameworks!

	pod 'RxSwift'
	pod 'RxCocoa'
	pod 'Kingfisher'
	pod 'RxDataSources'
	pod 'SwiftLint'
    pod 'Alamofire'
    pod 'RxAlamofire'
    pod 'SwiftyJSON'

end

target 'GoJekContact' do

	common_pods

  target 'GoJekContactTests' do
    inherit! :search_paths
  end

  target 'GoJekContactUITests' do
    inherit! :search_paths
  end

end
